apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
  labels:
    app: webapp
    type: front-end
spec:
  template:
    metadata:
      name: web-pod
      labels:
        app: webapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3